<?php

namespace Modules\Absence\Entities;

use Modules\Acl\Entities\User;
use Modules\Absence\Entities\Absent;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Mission extends Model
{
    protected $guarded = [];

    use HasFactory;


    public function omAutogenerated() {
        return $this->hasMany('App\Models\OmAutogenerated', 'missions_id');
    }
    
    public function department()
    {
        // return $this->belongsTo(Department::class, 'departments_id');
    }

    public function absence()
    {
        return $this->hasOne(Absent::class, 'missions_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'mission_head_id');
    }

}
