<?php

namespace Modules\Absence\Entities;

use Modules\Acl\Entities\User;
use Illuminate\Database\Eloquent\Model;
use Modules\Absence\Entities\Mission;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class OmAutogenerated extends Model
{
    protected $guarded = [];
    use HasFactory;


    public function mission() {
        return $this->belongsTo(Mission::class, 'missions_id');
    }
    
    public function user() {
        return $this->belongsTo(User::class, 'users_id');
    }

}
